name: biography1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^5.0.0
  firebase_auth: ^1.0.1
  provider: ^5.0.0
  image_picker: ^0.7.2+1
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter_easyloading: ^3.0.0
  loading: ^1.0.2
  confirm_dialog: ^1.0.0
  connectivity: ^3.0.3
  cached_network_image: ^2.5.1
  data_connection_checker: ^0.3.4
  stripe_payment: ^1.0.10
  fluttertoast: ^7.1.6
  shared_preferences: ^2.0.5
  http_auth: ^1.0.0
  webview_flutter: ^2.0.4
  double_back_to_close: ^1.0.2+mit



dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^2.5.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
